// Juan Tamariz's Mnemonica stack, positions 1–52.
// Four sectors train positions 1–13, 14–26, 27–39, and 40–52.
const MNEMONICA_STACK = [
  ['4','clubs'],['2','hearts'],['7','diamonds'],['3','clubs'],['4','hearts'],['6','diamonds'],['A','spades'],['5','hearts'],['9','spades'],['2','spades'],['Q','hearts'],['3','diamonds'],['Q','clubs'],
  ['8','hearts'],['6','spades'],['5','spades'],['9','hearts'],['K','clubs'],['2','diamonds'],['J','hearts'],['3','spades'],['8','spades'],['6','hearts'],['10','clubs'],['5','diamonds'],['K','diamonds'],
  ['2','clubs'],['3','hearts'],['8','diamonds'],['5','clubs'],['K','spades'],['J','diamonds'],['8','clubs'],['10','spades'],['K','hearts'],['J','clubs'],['7','spades'],['10','hearts'],['A','diamonds'],
  ['4','spades'],['7','hearts'],['4','diamonds'],['A','clubs'],['9','clubs'],['J','spades'],['Q','diamonds'],['7','clubs'],['Q','spades'],['10','diamonds'],['6','clubs'],['A','hearts'],['9','diamonds']
];
const REDFORD_STACK = [
  ['Q','hearts'],['2','spades'],['5','diamonds'],['8','clubs'],['J','hearts'],['K','spades'],['10','hearts'],['7','clubs'],['4','diamonds'],['A','spades'],['8','hearts'],['5','clubs'],['2','diamonds'],
  ['Q','spades'],['9','hearts'],['6','clubs'],['3','diamonds'],['10','spades'],['7','hearts'],['4','clubs'],['A','diamonds'],['J','spades'],['9','spades'],['6','hearts'],['3','clubs'],['K','diamonds'],
  ['Q','diamonds'],['10','diamonds'],['7','spades'],['4','hearts'],['A','clubs'],['J','diamonds'],['8','spades'],['5','hearts'],['2','clubs'],['2','hearts'],['Q','clubs'],['9','diamonds'],['6','spades'],
  ['3','hearts'],['K','clubs'],['4','spades'],['A','hearts'],['J','clubs'],['8','diamonds'],['5','spades'],['3','spades'],['K','hearts'],['10','clubs'],['7','diamonds'],['6','diamonds'],['9','clubs']
];
const ARONSON_STACK = [
  ['J','spades'],['K','clubs'],['5','clubs'],['2','hearts'],['9','spades'],['A','spades'],['3','hearts'],['6','clubs'],['8','diamonds'],['A','clubs'],['10','spades'],['5','hearts'],['2','diamonds'],
  ['K','diamonds'],['7','diamonds'],['8','clubs'],['3','spades'],['A','diamonds'],['7','spades'],['5','spades'],['Q','diamonds'],['A','hearts'],['8','spades'],['3','diamonds'],['7','hearts'],['Q','hearts'],
  ['5','diamonds'],['7','clubs'],['4','hearts'],['K','hearts'],['4','diamonds'],['10','diamonds'],['J','clubs'],['J','hearts'],['10','clubs'],['J','diamonds'],['4','spades'],['10','hearts'],['6','hearts'],
  ['3','clubs'],['2','spades'],['9','hearts'],['K','spades'],['6','spades'],['4','clubs'],['8','hearts'],['9','clubs'],['Q','spades'],['6','diamonds'],['Q','clubs'],['2','clubs'],['9','diamonds']
];
const STACKS = {
  mnemonica:{name:'MNEMONICA',cards:MNEMONICA_STACK},
  redford:{name:'REDFORD',cards:REDFORD_STACK},
  aronson:{name:'ARONSON',cards:ARONSON_STACK}
};
let MEMORY_STACK = MNEMONICA_STACK;
const SUITS = {clubs:'♣', hearts:'♥', spades:'♠', diamonds:'♦'};
const RANKS = ['A','2','3','4','5','6','7','8','9','10','J','Q','K'];
// Visual order is top-to-bottom. Memory positions still build bottom-to-top.
const FORTRESS_ROWS = [[10,11,12],[5,6,7,8,9],[0,1,2,3,4]];
const SECTOR_SIZE = 13;
const SECTOR_COUNT = 4;

const state = {stackKey:null,sector:0,phase:1,built:0,score:0,sectorStartScore:0,combo:1,selectedRank:null,health:Array(13).fill(0),paused:false,laserTimer:null,bombTimer:null,bomb:null,phaseTwoHits:0,recallQueue:[],reviewQueue:[],mastered:new Set(),misses:0,dronePenalty:0};
const $ = id => document.getElementById(id);
const sectorStart = () => state.sector * SECTOR_SIZE;
const globalPosition = localIndex => sectorStart() + localIndex + 1;
const sectorCard = localIndex => MEMORY_STACK[sectorStart() + localIndex];

function syncViewportHeight(){const height=window.visualViewport?.height||window.innerHeight;document.documentElement.style.setProperty('--app-height',`${Math.round(height)}px`)}
syncViewportHeight();window.addEventListener('resize',syncViewportHeight);window.visualViewport?.addEventListener('resize',syncViewportHeight);

function cardMarkup(card) {
  const [rank,suit]=card, red=suit==='hearts'||suit==='diamonds';
  return `<div class="card-face ${red?'red':''}"><span>${rank}<br>${SUITS[suit]}</span><em>${SUITS[suit]}</em><div class="health"><i style="width:100%"></i></div></div>`;
}

function renderFortress() {
  const root=$('fortress'); root.innerHTML='';
  FORTRESS_ROWS.forEach(positions=>{const row=document.createElement('div');row.className='fortress-row';
    positions.forEach(pos=>{const el=document.createElement('div');el.className='fortress-card';el.dataset.position=String(globalPosition(pos)).padStart(2,'0');el.dataset.index=pos;
      if(state.health[pos]>0){el.classList.add('built');el.innerHTML=cardMarkup(sectorCard(pos));el.querySelector('.health i').style.width=`${state.health[pos]}%`;if(state.health[pos]<100){const stage=Math.min(4,Math.ceil((100-state.health[pos])/20));el.classList.add('damaged',`damage-${stage}`);el.querySelector('.card-face').insertAdjacentHTML('beforeend','<i class="scorch"></i><i class="crack"></i>');if(state.health[pos]<=25){el.classList.add('critical');el.insertAdjacentHTML('beforeend','<span class="card-flames"><i></i><i></i><i></i><b></b></span>')}}}
      if(pos===state.built && state.phase===1)el.classList.add('next');
      el.addEventListener('dragover',e=>e.preventDefault());el.addEventListener('drop',e=>{e.preventDefault();placeCard(e.dataTransfer.getData('rank'));});row.appendChild(el)});if(positions.every(pos=>state.health[pos]>0))row.classList.add('completed');root.appendChild(row)});
  if(state.health.every(health=>health>0))root.classList.add('station-complete');
  $('battlefield').classList.toggle('danger',state.health.some(health=>health>0&&health<=25));
}

function renderControls(){
  $('rankRow').innerHTML=RANKS.map(rank=>`<button class="rank-button ${rank===state.selectedRank?'selected':''}" data-rank="${rank}">${rank}</button>`).join('');
  document.querySelectorAll('.rank-button').forEach(b=>b.onclick=()=>{if(state.paused)return;state.selectedRank=b.dataset.rank;renderControls();sound('select')});
  $('suitRow').innerHTML=Object.entries(SUITS).map(([name,symbol])=>`<button class="suit-button ${(name==='hearts'||name==='diamonds')?'red':''}" data-suit="${name}" ${state.selectedRank?'':'disabled'}><span>${symbol}</span><small>${name.toUpperCase()}</small></button>`).join('');
  document.querySelectorAll('.suit-button').forEach(b=>b.onclick=()=>placeCard(b.dataset.suit));
}

function placeCard(suit){if(state.paused||state.phase!==1||state.built>=13||!state.selectedRank)return;const expected=sectorCard(state.built),chosenRank=state.selectedRank;state.selectedRank=null;
  if(chosenRank===expected[0]&&suit===expected[1]){state.health[state.built]=100;state.built++;state.score+=100*state.combo;state.combo=Math.min(9,state.combo+1);flashMessage(`${chosenRank} OF ${suit.toUpperCase()} · SECURED`,true);updateUI();renderFortress();renderControls();sound('build');
    if(state.built===13)setTimeout(showPhaseComplete,350);
  }else{state.combo=1;state.score=Math.max(0,state.score-25);flashMessage('MEMORY MISMATCH',false);updateUI();renderControls();sound('error')}
}

function fireLaser(){if(state.paused||state.phase!==1||state.built===0)return;
  // Attack the newest wall segment so a destroyed card becomes the next card to rebuild.
  const target=state.built-1,card=document.querySelector(`[data-index="${target}"]`);if(!card)return;
  const field=$('battlefield').getBoundingClientRect(), cannon=document.querySelector('.ship-cannon').getBoundingClientRect(), rect=card.getBoundingClientRect(),startX=cannon.left-field.left+cannon.width/2,startY=cannon.bottom-field.top-2,endX=rect.left-field.left+rect.width/2,endY=rect.top-field.top+rect.height/2,dx=endX-startX,dy=endY-startY,length=Math.hypot(dx,dy),angle=Math.atan2(dy,dx)*180/Math.PI;const laser=document.createElement('i');laser.className='laser';laser.style.left=`${startX}px`;laser.style.top=`${startY}px`;laser.style.width=`${length}px`;laser.style.transform=`rotate(${angle}deg) scaleX(0)`;$('laserLayer').appendChild(laser);
  sound('laser');
  requestAnimationFrame(()=>requestAnimationFrame(()=>{laser.style.transform=`rotate(${angle}deg) scaleX(1)`}));
  setTimeout(()=>{laser.remove();damageCard(target,15);const impact=document.createElement('i');impact.className='impact';impact.style.left=`${rect.left-field.left+rect.width/2-14}px`;impact.style.top=`${rect.top-field.top+rect.height/2-14}px`;$('laserLayer').appendChild(impact);setTimeout(()=>impact.remove(),400)},430)
}

function damageCard(index,amount){if(state.phase!==1)return;const field=$('battlefield');field.classList.remove('battle-shake');void field.offsetWidth;field.classList.add('battle-shake');setTimeout(()=>field.classList.remove('battle-shake'),260);state.health[index]=Math.max(0,state.health[index]-amount);sound('impact');const destroyed=state.health[index]===0;if(destroyed){explodeCard(index);state.built=Math.max(0,state.built-1);state.combo=1;flashMessage(`POSITION ${String(globalPosition(index)).padStart(2,'0')} DESTROYED · REBUILD`,false);sound('breach')}else if(state.health[index]<=25){flashMessage(`POSITION ${String(globalPosition(index)).padStart(2,'0')} CRITICAL · REPAIR NOW`,false);sound('burn')}renderFortress();updateUI()}
function scheduleLaser(){clearTimeout(state.laserTimer);if(state.phase!==1)return;const burst=Math.random()<.18,delay=burst?450+Math.random()*300:1400+Math.random()*1200;state.laserTimer=setTimeout(()=>{fireLaser();scheduleLaser()},delay)}
function explodeCard(index){const card=document.querySelector(`[data-index="${index}"]`),field=$('battlefield').getBoundingClientRect();if(!card)return;const rect=card.getBoundingClientRect(),blast=document.createElement('span');blast.className='card-explosion';blast.style.left=`${rect.left-field.left+rect.width/2}px`;blast.style.top=`${rect.top-field.top+rect.height/2}px`;blast.innerHTML='<b></b><em></em>'+Array.from({length:16},(_,i)=>{const angle=Math.PI*2*i/16,distance=28+Math.random()*44;return `<i style="--dx:${Math.cos(angle)*distance}px;--dy:${Math.sin(angle)*distance}px;--rot:${Math.round(Math.random()*360)}deg;--delay:${Math.random()*.08}s"></i>`}).join('');$('laserLayer').appendChild(blast);setTimeout(()=>blast.remove(),900)}

function showPhaseComplete(){clearTimeout(state.laserTimer);$('leaderboard').classList.add('hidden');$('modal').classList.remove('hidden');$('modalEyebrow').textContent=`SECTOR ${String(state.sector+1).padStart(2,'0')} · FORTRESS COMPLETE`;$('modalTitle').textContent='FORTRESS ONLINE';$('modalText').textContent=`Positions ${globalPosition(0)}–${globalPosition(12)} are secure. Now recall all 13 cards.`;$('modalButton').textContent='BEGIN RECALL';$('modalButton').onclick=startPhaseTwo}
function shuffle(values){for(let i=values.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[values[i],values[j]]=[values[j],values[i]]}return values}
function startPhaseTwo(){$('modal').classList.add('hidden');state.phase=2;state.phaseTwoHits=0;state.bomb=null;state.recallQueue=shuffle(Array.from({length:13},(_,i)=>i));state.reviewQueue=[];state.mastered=new Set();state.misses=0;state.dronePenalty=0;$('battleMessage').textContent='IDENTIFY THE FALLING CARD';$('buildControls').classList.add('hidden');$('phaseTwoControls').classList.remove('hidden');$('defenseTurrets').classList.remove('hidden');$('positionGrid').innerHTML=Array.from({length:13},(_,i)=>`<button class="position-button" data-position="${i}">${String(globalPosition(i)).padStart(2,'0')}</button>`).join('');document.querySelectorAll('.position-button').forEach(b=>b.onclick=()=>intercept(Number(b.dataset.position)));updateUI();spawnBomb();state.bombTimer=setInterval(tickBomb,50)}
function nextRecallCard(){if(!state.recallQueue.length&&state.reviewQueue.length){state.recallQueue=shuffle([...new Set(state.reviewQueue)].filter(i=>!state.mastered.has(i)));state.reviewQueue=[];flashMessage('REVIEW ROUND',true)}while(state.recallQueue.length&&state.mastered.has(state.recallQueue[0]))state.recallQueue.shift();return state.recallQueue.shift()}
function spawnBomb(){if(state.paused||state.bomb)return;if(state.mastered.size===13){showVictory();return}const index=nextRecallCard();if(index===undefined)return;const el=document.createElement('div'),card=sectorCard(index),fieldWidth=$('battlefield').clientWidth,baseX=58+Math.random()*Math.max(1,fieldWidth-154),red=card[1]==='hearts'||card[1]==='diamonds';el.className='bomb drone';el.innerHTML=`<i class="drone-wing left"></i><i class="drone-wing right"></i><span class="drone-eye left"></span><span class="drone-eye right"></span><div class="drone-core"><b class="${red?'red':''}">${card[0]}<span>${SUITS[card[1]]}</span></b></div><span class="drone-thruster"></span>`;el.style.left=`${baseX}px`;$('bombLayer').appendChild(el);state.bomb={index,el,y:-74,baseX,amplitude:70+Math.random()*45,phase:Math.random()*Math.PI*2,zigzagSpeed:.1+Math.random()*.08,missed:false,fired:false};updateUI()}
function markMissed(index){if(!state.mastered.has(index)&&!state.reviewQueue.includes(index))state.reviewQueue.push(index);state.misses++;state.combo=1}
function tickBomb(){if(state.paused)return;if(!state.bomb){spawnBomb();return}const field=$('battlefield'),drone=state.bomb;drone.y+=Math.max(1.05,field.clientHeight/15000*50);drone.phase+=drone.zigzagSpeed;const rawX=drone.baseX+Math.sin(drone.phase)*drone.amplitude,x=Math.max(3,Math.min(field.clientWidth-drone.el.offsetWidth-3,rawX)),bank=Math.cos(drone.phase)*-13;drone.el.style.top=`${drone.y}px`;drone.el.style.left=`${x}px`;drone.el.style.transform=`rotate(${bank}deg)`;trackTurrets(drone.el);const floor=field.clientHeight-drone.el.offsetHeight-10;if(!drone.engaged&&!drone.fired&&drone.y>floor*.68){drone.fired=true;fireDroneLaser(drone)}if(!drone.engaged&&drone.y>floor){markMissed(drone.index);drone.el.remove();state.bomb=null;flashMessage('DRONE BREACH · ADDED TO REVIEW',false);sound('breach');updateUI();setTimeout(spawnBomb,450)}}
function trackTurrets(droneEl){const target=droneEl.getBoundingClientRect();document.querySelectorAll('.turret-head').forEach(head=>{const rect=head.getBoundingClientRect(),dx=target.left+target.width/2-(rect.left+rect.width/2),dy=target.top+target.height/2-(rect.top+rect.height/2),angle=Math.atan2(dy,dx)*180/Math.PI;head.style.transform=`rotate(${angle+90}deg)`})}
function fireDroneLaser(drone){const surviving=state.health.map((health,index)=>({health,index})).filter(card=>card.health>0);if(!surviving.length)return;const lowestHealth=Math.min(...surviving.map(card=>card.health)),weakest=surviving.filter(card=>card.health===lowestHealth),target=weakest[Math.floor(Math.random()*weakest.length)].index,card=document.querySelector(`[data-index="${target}"]`),field=$('battlefield').getBoundingClientRect(),source=drone.el.querySelector('.drone-core').getBoundingClientRect(),rect=card?.getBoundingClientRect();if(!rect)return;const startX=source.left-field.left+source.width/2,startY=source.top-field.top+source.height/2,endX=rect.left-field.left+rect.width/2,endY=rect.top-field.top+rect.height/2,dx=endX-startX,dy=endY-startY,length=Math.hypot(dx,dy),angle=Math.atan2(dy,dx)*180/Math.PI,beam=document.createElement('i');beam.className='drone-laser';beam.style.cssText=`left:${startX}px;top:${startY}px;width:${length}px;transform:rotate(${angle}deg) scaleX(0)`;$('laserLayer').appendChild(beam);sound('enemyLaser');requestAnimationFrame(()=>requestAnimationFrame(()=>beam.style.transform=`rotate(${angle}deg) scaleX(1)`));setTimeout(()=>{beam.remove();hitFortressFromDrone(target)},340)}
function hitFortressFromDrone(index){if(state.phase!==2||state.health[index]<=0)return;state.health[index]=Math.max(0,state.health[index]-35);if(state.health[index]===0){explodeCard(index);state.dronePenalty+=500;state.score=Math.max(0,state.score-500);showPointPenalty(index,500);flashMessage(`POSITION ${String(globalPosition(index)).padStart(2,'0')} DESTROYED · −500 POINTS`,false);sound('breach')}else{sound('impact')}renderFortress();updateUI()}
function showPointPenalty(index,points){const card=document.querySelector(`[data-index="${index}"]`),field=$('battlefield').getBoundingClientRect(),rect=card?.getBoundingClientRect(),popup=document.createElement('strong');popup.className='point-penalty';popup.textContent=`−${points}`;popup.style.left=`${rect?rect.left-field.left+rect.width/2:field.width/2}px`;popup.style.top=`${rect?rect.top-field.top:field.height*.65}px`;$('laserLayer').appendChild(popup);setTimeout(()=>popup.remove(),1200)}
function intercept(position){if(state.paused||!state.bomb||state.bomb.engaged)return;if(position===state.bomb.index){const masteredIndex=state.bomb.index;state.bomb.engaged=true;state.score+=200*state.combo;state.combo=Math.min(9,state.combo+1);state.mastered.add(masteredIndex);state.reviewQueue=state.reviewQueue.filter(i=>i!==masteredIndex);state.phaseTwoHits=state.mastered.size;state.bomb.el.classList.add('targeted');flashMessage('GROUND DEFENSE LOCK · +200',true);shootDownDrone(()=>{state.bomb=null;if(state.mastered.size===13)showVictory();else spawnBomb()})}else{if(!state.bomb.missed){state.bomb.missed=true;markMissed(state.bomb.index)}state.score=Math.max(0,state.score-50);flashMessage('WRONG · CARD QUEUED FOR REVIEW',false);sound('error')}updateUI()}
function shootDownDrone(onComplete){const field=$('battlefield').getBoundingClientRect(),droneEl=state.bomb.el,rect=droneEl.getBoundingClientRect(),heads=[...document.querySelectorAll('.turret-head')],targetX=rect.left+rect.width/2,targetY=rect.top+rect.height/2,head=heads.sort((a,b)=>{const ar=a.getBoundingClientRect(),br=b.getBoundingClientRect();return Math.hypot(targetX-ar.left-ar.width/2,targetY-ar.top-ar.height/2)-Math.hypot(targetX-br.left-br.width/2,targetY-br.top-br.height/2)})[0],source=head.getBoundingClientRect(),centerX=source.left+source.width/2,centerY=source.top+source.height/2,worldDx=targetX-centerX,worldDy=targetY-centerY,worldLength=Math.hypot(worldDx,worldDy),startWorldX=centerX+worldDx/worldLength*25,startWorldY=centerY+worldDy/worldLength*25,startX=startWorldX-field.left,startY=startWorldY-field.top,endX=targetX-field.left,endY=targetY-field.top,dx=endX-startX,dy=endY-startY,length=Math.hypot(dx,dy),angle=Math.atan2(dy,dx)*180/Math.PI,beam=document.createElement('i'),muzzle=document.createElement('i');head.closest('.defense-turret').classList.add('firing');beam.className='ground-laser';beam.style.cssText=`left:${startX}px;top:${startY}px;width:${length}px;transform:rotate(${angle}deg) scaleX(0)`;muzzle.className='ground-muzzle';muzzle.style.left=`${startX}px`;muzzle.style.top=`${startY}px`;$('laserLayer').append(muzzle,beam);sound('groundLaser');requestAnimationFrame(()=>requestAnimationFrame(()=>beam.style.transform=`rotate(${angle}deg) scaleX(1)`));setTimeout(()=>{beam.remove();muzzle.remove();head.closest('.defense-turret').classList.remove('firing');explodeDrone(droneEl);droneEl.remove();sound('droneBlast');setTimeout(onComplete,260)},390)}
function explodeDrone(droneEl){const field=$('battlefield').getBoundingClientRect(),rect=droneEl.getBoundingClientRect(),blast=document.createElement('span');blast.className='drone-explosion';blast.style.left=`${rect.left-field.left+rect.width/2}px`;blast.style.top=`${rect.top-field.top+rect.height/2}px`;blast.innerHTML='<b></b><em></em>'+Array.from({length:18},(_,i)=>{const angle=Math.PI*2*i/18,distance=35+Math.random()*55;return `<i style="--dx:${Math.cos(angle)*distance}px;--dy:${Math.sin(angle)*distance}px;--rot:${Math.round(Math.random()*540)}deg;--delay:${Math.random()*.07}s"></i>`}).join('');$('laserLayer').appendChild(blast);setTimeout(()=>blast.remove(),1050)}
function showVictory(){clearInterval(state.bombTimer);state.bomb?.el.remove();state.bomb=null;$('defenseTurrets').classList.add('hidden');showLeaderboard(state.sector===SECTOR_COUNT-1)}
function leaderboardKey(){return `memory-fortress-${state.stackKey}-sector-${state.sector+1}-scores`}
function getHighScores(){try{return JSON.parse(localStorage.getItem(leaderboardKey())||'[]').filter(x=>Number.isFinite(x.score)).sort((a,b)=>b.score-a.score).slice(0,3)}catch{return[]}}
function showLeaderboard(finalSector){const sectorScore=state.score-state.sectorStartScore,previous=getHighScores(),previousBest=previous[0]?.score??-1,qualifies=previous.length<3||sectorScore>previous[previous.length-1].score,isNumberOne=sectorScore>previousBest,beatPrevious=isNumberOne&&previousBest>=0;let scores=previous;if(qualifies){scores=[...previous,{score:sectorScore,date:new Date().toISOString()}].sort((a,b)=>b.score-a.score).slice(0,3);try{localStorage.setItem(leaderboardKey(),JSON.stringify(scores))}catch{}}
  $('modal').classList.remove('hidden');$('leaderboard').classList.remove('hidden');$('modalEyebrow').textContent=isNumberOne?(beatPrevious?'YOU BEAT YOUR BEST!':'FIRST SECTOR RECORD'):`SECTOR ${String(state.sector+1).padStart(2,'0')} COMPLETE`;$('modalTitle').textContent=isNumberOne?'NEW HIGH SCORE!':'SECTOR LEADERBOARD';$('modalText').textContent=`${STACKS[state.stackKey].name} positions ${globalPosition(0)}–${globalPosition(12)} mastered${state.misses?` with ${state.misses} reviewed miss${state.misses===1?'':'es'}`:' with a perfect recall'}${state.dronePenalty?` · ${state.dronePenalty} drone-damage points lost`:''}!`;$('runScore').textContent=String(sectorScore).padStart(4,'0');$('scoreResult').textContent=isNumberOne?(beatPrevious?'#1 · BETTER THAN EVER!':'#1 · FIRST RECORD'):qualifies?'TOP 3 · RECORDED':'THIS RUN · NOT RECORDED';$('leaderboardList').innerHTML=scores.map((entry,i)=>`<li class="${entry.score===sectorScore&&qualifies?'current':''}"><b>${i+1}</b><strong>${String(entry.score).padStart(4,'0')}</strong><span>SECTOR ${state.sector+1}</span></li>`).join('');$('modalButton').textContent=finalSector?'FULL DECK COMPLETE · PLAY AGAIN':`CONTINUE TO ${globalPosition(12)+1}–${globalPosition(12)+13}`;$('modalButton').onclick=finalSector?restart:startNextSector;if(isNumberOne){sound('highscore');launchFireworks()}else sound('victory')}
function launchFireworks(){const layer=$('fireworksLayer'),colors=['#ff3b1f','#ff761a','#ffc928','#ff5138'];layer.innerHTML='';layer.classList.add('active');for(let burst=0;burst<8;burst++){setTimeout(()=>{const x=12+Math.random()*76,y=12+Math.random()*55;for(let i=0;i<18;i++){const spark=document.createElement('i'),angle=Math.PI*2*i/18,distance=45+Math.random()*75;spark.style.cssText=`--x:${x}vw;--y:${y}vh;--dx:${Math.cos(angle)*distance}px;--dy:${Math.sin(angle)*distance}px;--color:${colors[Math.floor(Math.random()*colors.length)]};--delay:${Math.random()*.08}s`;layer.appendChild(spark);setTimeout(()=>spark.remove(),1100)}sound('pop')},burst*230)}setTimeout(()=>{layer.classList.remove('active');layer.innerHTML=''},3000)}
function startNextSector(){state.sector++;state.sectorStartScore=state.score;state.phase=1;state.built=0;state.health=Array(13).fill(0);state.selectedRank=null;state.combo=1;state.bomb=null;state.phaseTwoHits=0;state.mastered=new Set();state.misses=0;$('modal').classList.add('hidden');$('phaseTwoControls').classList.add('hidden');$('defenseTurrets').classList.add('hidden');$('buildControls').classList.remove('hidden');renderFortress();renderControls();updateUI();flashMessage(`SECTOR ${state.sector+1} · BUILD POSITION ${globalPosition(0)}`,true);scheduleLaser()}
function flashMessage(text,good){const el=$('battleMessage');el.textContent=text;el.style.color=good?'var(--cyan)':'var(--danger)';clearTimeout(el._timer);el._timer=setTimeout(()=>{el.textContent=state.phase===1?`FORTIFY POSITION ${String(globalPosition(state.built)).padStart(2,'0')}`:'IDENTIFY THE FALLING CARD';el.style.color='var(--cyan)'},900)}
function updateUI(){const sectorNumber=String(state.sector+1).padStart(2,'0'),stackName=state.stackKey?STACKS[state.stackKey].name:'SELECT STACK';$('sectorLabel').textContent=`${stackName} // SECTOR ${sectorNumber} // ${String(globalPosition(0)).padStart(2,'0')}–${String(globalPosition(12)).padStart(2,'0')}`;$('phaseLabel').textContent=`${sectorNumber} · ${state.phase===1?'BUILD':'RECALL'}`;$('scoreLabel').textContent=String(state.score).padStart(4,'0');$('comboLabel').textContent=`×${state.combo}`;const shield=state.built?Math.round(state.health.slice(0,state.built).reduce((a,b)=>a+b,0)/state.built):100;$('statLabel').textContent=state.phase===1?'SHIELD':'MISSES';$('statValue').textContent=state.phase===1?`${shield}%`:String(state.misses);$('progressText').textContent=state.phase===1?`${state.built} / 13 BUILT`:`${state.phaseTwoHits} / 13 MASTERED`;$('progressBar').style.width=`${state.phase===1?state.built/13*100:state.phaseTwoHits/13*100}%`;if(state.phase===2&&$('recallStatus'))$('recallStatus').textContent=`${13-state.mastered.size} REMAIN`;
  if(state.built<13){$('targetPosition').textContent=String(globalPosition(state.built)).padStart(2,'0');const c=sectorCard(state.built);$('targetCard').textContent=c?`${c[0]}${SUITS[c[1]]}`:'✓'}$('pauseButton').textContent=state.paused?'▶ RESUME':'Ⅱ PAUSE'}
function restart(){location.reload()}
function tone(freq,duration,volume=.045,type='sine',delay=0,endFreq=freq){if($('soundButton').dataset.muted==='true')return;try{const ctx=tone.ctx||(tone.ctx=new AudioContext()),start=ctx.currentTime+delay,osc=ctx.createOscillator(),gain=ctx.createGain();osc.type=type;osc.frequency.setValueAtTime(freq,start);osc.frequency.exponentialRampToValueAtTime(Math.max(20,endFreq),start+duration);gain.gain.setValueAtTime(volume,start);gain.gain.exponentialRampToValueAtTime(.001,start+duration);osc.connect(gain).connect(ctx.destination);osc.start(start);osc.stop(start+duration)}catch{}}
function noise(duration=.14,volume=.07,delay=0){if($('soundButton').dataset.muted==='true')return;try{const ctx=tone.ctx||(tone.ctx=new AudioContext()),start=ctx.currentTime+delay,buffer=ctx.createBuffer(1,ctx.sampleRate*duration,ctx.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=(Math.random()*2-1)*(1-i/data.length);const source=ctx.createBufferSource(),gain=ctx.createGain(),filter=ctx.createBiquadFilter();source.buffer=buffer;filter.type='lowpass';filter.frequency.value=900;gain.gain.setValueAtTime(volume,start);gain.gain.exponentialRampToValueAtTime(.001,start+duration);source.connect(filter).connect(gain).connect(ctx.destination);source.start(start)}catch{}}
function sound(name){if(name==='select'){tone(330,.045,.018,'sine')}else if(name==='laser'){tone(1050,.13,.032,'sawtooth',0,240);tone(1450,.08,.018,'square',0,500)}else if(name==='enemyLaser'){tone(680,.18,.04,'square',0,140);tone(430,.2,.025,'sawtooth',0,90)}else if(name==='groundLaser'){tone(190,.16,.035,'sine',0,740);tone(1250,.28,.045,'sawtooth',.1,260)}else if(name==='droneBlast'){noise(.3,.09);tone(130,.3,.055,'square',0,38)}else if(name==='impact'){tone(150,.12,.045,'square',0,55)}else if(name==='burn'){noise(.34,.025);tone(92,.32,.018,'sawtooth',0,52)}else if(name==='build'){tone(440,.08);tone(660,.12,.04,'sine',.07)}else if(name==='intercept'){tone(720,.07,.04,'square');tone(1080,.13,.04,'sine',.06)}else if(name==='error'){tone(170,.12,.04,'sawtooth',0,95)}else if(name==='breach'){tone(120,.28,.06,'sawtooth',0,35)}else if(name==='victory'){[523,659,784,1047].forEach((f,i)=>tone(f,.22,.04,'sine',i*.11))}else if(name==='pop'){noise(.1,.05);tone(180,.1,.025,'square',0,55)}else if(name==='highscore'){noise(.28,.09);noise(.22,.08,.18);[392,523,659,784,1047].forEach((f,i)=>tone(f,.3,.045,'sine',i*.1))}}

$('restartButton').onclick=restart;$('pauseButton').onclick=()=>{state.paused=!state.paused;updateUI()};$('soundButton').onclick=e=>{const muted=e.currentTarget.dataset.muted!=='true';e.currentTarget.dataset.muted=muted;e.currentTarget.textContent=muted?'MUTE':'◖))'};
document.querySelectorAll('[data-stack]').forEach(button=>button.onclick=()=>{state.stackKey=button.dataset.stack;MEMORY_STACK=STACKS[state.stackKey].cards;$('stackChooser').classList.add('hidden');state.sector=0;state.phase=1;state.built=0;state.score=0;state.sectorStartScore=0;state.health=Array(13).fill(0);renderFortress();renderControls();updateUI();flashMessage(`${STACKS[state.stackKey].name} · SECTOR 1 READY`,true);scheduleLaser();sound('build')});
renderFortress();renderControls();updateUI();
