// Juan Tamariz's Mnemonica stack, positions 1–52.
// Four sectors train positions 1–13, 14–26, 27–39, and 40–52.
const MNEMONICA_STACK = [
  ['4','clubs'],['2','hearts'],['7','diamonds'],['3','clubs'],['4','hearts'],['6','diamonds'],['A','spades'],['5','hearts'],['9','spades'],['2','spades'],['Q','hearts'],['3','diamonds'],['Q','clubs'],
  ['8','hearts'],['6','spades'],['5','spades'],['9','hearts'],['K','clubs'],['2','diamonds'],['J','hearts'],['3','spades'],['8','spades'],['6','hearts'],['10','clubs'],['5','diamonds'],['K','diamonds'],
  ['2','clubs'],['3','hearts'],['8','diamonds'],['5','clubs'],['K','spades'],['J','diamonds'],['8','clubs'],['10','spades'],['K','hearts'],['J','clubs'],['7','spades'],['10','hearts'],['A','diamonds'],
  ['4','spades'],['7','hearts'],['4','diamonds'],['A','clubs'],['9','clubs'],['J','spades'],['Q','diamonds'],['7','clubs'],['Q','spades'],['10','diamonds'],['6','clubs'],['A','hearts'],['9','diamonds']
];
const REDFORD_STACK = [
  ['Q','hearts'],['2','spades'],['5','diamonds'],['8','clubs'],['J','hearts'],['K','spades'],['10','hearts'],['7','clubs'],['4','diamonds'],['A','spades'],['8','hearts'],['5','clubs'],['2','diamonds'],
  ['Q','spades'],['9','hearts'],['6','clubs'],['3','diamonds'],['10','spades'],['7','hearts'],['4','clubs'],['A','diamonds'],['J','spades'],['9','spades'],['6','hearts'],['3','clubs'],['K','diamonds'],
  ['Q','diamonds'],['10','diamonds'],['7','spades'],['4','hearts'],['A','clubs'],['J','diamonds'],['8','spades'],['5','hearts'],['2','clubs'],['2','hearts'],['Q','clubs'],['9','diamonds'],['6','spades'],
  ['3','hearts'],['K','clubs'],['4','spades'],['A','hearts'],['J','clubs'],['8','diamonds'],['5','spades'],['3','spades'],['K','hearts'],['10','clubs'],['7','diamonds'],['6','diamonds'],['9','clubs']
];
const ARONSON_STACK = [
  ['J','spades'],['K','clubs'],['5','clubs'],['2','hearts'],['9','spades'],['A','spades'],['3','hearts'],['6','clubs'],['8','diamonds'],['A','clubs'],['10','spades'],['5','hearts'],['2','diamonds'],
  ['K','diamonds'],['7','diamonds'],['8','clubs'],['3','spades'],['A','diamonds'],['7','spades'],['5','spades'],['Q','diamonds'],['A','hearts'],['8','spades'],['3','diamonds'],['7','hearts'],['Q','hearts'],
  ['5','diamonds'],['7','clubs'],['4','hearts'],['K','hearts'],['4','diamonds'],['10','diamonds'],['J','clubs'],['J','hearts'],['10','clubs'],['J','diamonds'],['4','spades'],['10','hearts'],['6','hearts'],
  ['3','clubs'],['2','spades'],['9','hearts'],['K','spades'],['6','spades'],['4','clubs'],['8','hearts'],['9','clubs'],['Q','spades'],['6','diamonds'],['Q','clubs'],['2','clubs'],['9','diamonds']
];
const STACKS = {
  mnemonica:{name:'MNEMONICA',cards:MNEMONICA_STACK},
  redford:{name:'REDFORD',cards:REDFORD_STACK},
  aronson:{name:'ARONSON',cards:ARONSON_STACK}
};
let MEMORY_STACK = MNEMONICA_STACK;
const SUITS = {clubs:'♣', hearts:'♥', spades:'♠', diamonds:'♦'};
const RANKS = ['A','2','3','4','5','6','7','8','9','10','J','Q','K'];
// Visual order is top-to-bottom. Memory positions still build bottom-to-top.
const FORTRESS_ROWS = [[10,11,12],[5,6,7,8,9],[0,1,2,3,4]];
const SECTOR_SIZE = 13;
const SECTOR_COUNT = 4;
const SAFE_DAMAGE_VARIANTS = [1,3,5];

const DEFEAT_TAUNTS = [
  'Are you even trying?',
  'You’ll never forget that.',
  'The raiders appreciate your cooperation.',
  'Your fortress had a good five minutes.',
  'Bold strategy. Terrible outcome.',
  'The mothership barely noticed.',
  'That could have gone better.',
  'The cards deserved better.',
  'Memory status: critically unavailable.',
  'The raiders would like another turn.',
  'You built them a very nice target.',
  'At least the explosions looked cool.',
  'Your turrets have requested a new commander.',
  'The fortress is filing a complaint.',
  'Maybe the cards shuffled themselves.',
  'Excellent work, if surrender was the plan.',
  'The enemy has rated your defense one star.',
  'That fortress was more of a suggestion.',
  'Good news: nobody will remember that performance.'
];
const STACK_CREATORS = {mnemonica:'Juan Tamariz',redford:'Patrick Redford',aronson:'Simon Aronson'};
function randomDefeatTaunt(){const choices=[...DEFEAT_TAUNTS],creator=STACK_CREATORS[state.stackKey];if(creator)choices.push(`Somewhere, ${creator} just felt a disturbance.`);return choices[Math.floor(Math.random()*choices.length)]}

const state = {stackKey:null,mode:null,forceTutorial:false,positionOrder:Array.from({length:52},(_,i)=>i),dronePositionOrder:Array.from({length:52},(_,i)=>i),positionEntry:'',tutorialStep:0,tutorialKind:'build',sector:0,phase:1,built:0,baysBuilt:true,turretsDeployed:false,shipEntered:false,cannonIndex:Math.floor(Math.random()*3),score:0,sectorStartScore:0,recallStartScore:0,combo:1,selectedRank:null,health:Array(13).fill(0),paused:false,ending:false,laserTimer:null,bombTimer:null,bomb:null,phaseTwoHits:0,recallQueue:[],reviewQueue:[],mastered:new Set(),misses:0,damagePenalty:0,droneDestroyed:0,eliteRaiderIndex:null,eliteRaiderSpawned:false,buildStartedAt:null,buildElapsed:null,recallStartedAt:null,recallElapsed:null,timeBonus:0,recallTimeBonus:0};
const $ = id => document.getElementById(id);
const formatTime = seconds => {if(seconds===null||seconds===undefined||!Number.isFinite(Number(seconds)))return '--:--.-';const safe=Math.max(0,Number(seconds)),minutes=Math.floor(safe/60),remainder=(safe%60).toFixed(1).padStart(4,'0');return `${String(minutes).padStart(2,'0')}:${remainder}`};
const buildTimeBonus = seconds => seconds<=20?1200:seconds<=30?1000:seconds<=40?800:seconds<=50?600:seconds<=60?400:seconds<=75?200:0;
const raiderTimeBonus = seconds => seconds<=25?1500:seconds<=35?1200:seconds<=50?900:seconds<=65?600:seconds<=85?300:seconds<=110?150:0;
function finishBuildTimer(){if(state.buildElapsed!==null)return;state.buildElapsed=(performance.now()-state.buildStartedAt)/1000;state.timeBonus=buildTimeBonus(state.buildElapsed);state.score+=state.timeBonus;updateUI()}
function finishRecallTimer(){if(state.recallElapsed!==null)return;state.recallElapsed=(performance.now()-state.recallStartedAt)/1000;state.recallTimeBonus=raiderTimeBonus(state.recallElapsed);state.score+=state.recallTimeBonus;updateUI()}
function sectorTimesText(build=state.buildElapsed,recall=state.recallElapsed){return `BUILD ${formatTime(build)} · RAIDERS ${formatTime(recall)}`}
const sectorStart = () => state.sector * SECTOR_SIZE;
const globalPosition = localIndex => state.positionOrder[sectorStart() + localIndex] + 1;
const sectorCard = localIndex => MEMORY_STACK[globalPosition(localIndex)-1];
const droneGlobalPosition = localIndex => state.mode==='super'?state.dronePositionOrder[sectorStart()+localIndex]+1:globalPosition(localIndex);
const droneCard = localIndex => MEMORY_STACK[droneGlobalPosition(localIndex)-1];
const sectorDescription = () => state.mode==='super'?'13 SHUFFLED POSITIONS':`${String(globalPosition(0)).padStart(2,'0')}–${String(globalPosition(12)).padStart(2,'0')}`;
const raiderHistoryKey = () => `memory-fortress-${state.stackKey}-${state.mode}-raider-history`;
function getRaiderHistory(){try{return JSON.parse(localStorage.getItem(raiderHistoryKey())||'{}')}catch{return{}}}
function recordRaiderResult(index,seconds,miss=false){const history=getRaiderHistory(),key=String(droneGlobalPosition(index)),entry=history[key]||{average:0,samples:0,misses:0};if(Number.isFinite(seconds)){entry.average=(entry.average*entry.samples+seconds)/(entry.samples+1);entry.samples++}if(miss)entry.misses++;history[key]=entry;try{localStorage.setItem(raiderHistoryKey(),JSON.stringify(history))}catch{}}
function chooseEliteRaider(){const history=getRaiderHistory(),candidates=Array.from({length:13},(_,index)=>{const entry=history[String(droneGlobalPosition(index))];return {index,score:entry?.samples?entry.average+(entry.misses||0)*4:null}}),known=candidates.filter(card=>card.score!==null).sort((a,b)=>b.score-a.score);if(!known.length)return Math.floor(Math.random()*13);const pool=known.slice(0,Math.min(3,known.length));return pool[Math.floor(Math.random()*pool.length)].index}
function makeDroneOrder(buildOrder){const groups=Array.from({length:4},(_,group)=>buildOrder.slice(group*13,group*13+13)),groupOrder=[0,1,2,3];do{shuffle(groupOrder)}while(groupOrder.some((group,index)=>group===index));return groupOrder.flatMap(group=>shuffle([...groups[group]]))}
function randomizeShipFlight(){const ship=$('ship'),between=(min,max)=>min+Math.random()*(max-min);for(let i=1;i<=3;i++){ship.style.setProperty(`--jink-y-${i}`,`${between(-3,7).toFixed(1)}px`);ship.style.setProperty(`--jink-bank-${i}`,`${between(-5,5).toFixed(1)}deg`)}}

function buildTutorialSlides(){const card=sectorCard(0),position=String(globalPosition(0)).padStart(2,'0'),rank=card[0],suit=card[1];return[
  {title:'WE’RE UNDER ATTACK',text:`Build the fortress! Match the corresponding card with the number it is in the stack. Position ${position} matches ${rank}${SUITS[suit]}.`,selectors:['.fortress-card.next','#targetCard'],labels:[`POSITION ${position}`,`CARD ${rank}${SUITS[suit]}`]},
  {title:'CHOOSE THE VALUE FIRST',text:`For ${rank}${SUITS[suit]}, tap ${rank} first.`,selectors:[`.rank-button[data-rank="${rank}"]`],labels:[`TAP VALUE ${rank}`]},
  {title:'THEN CHOOSE THE SUIT',text:`Tap ${SUITS[suit]} to lock ${rank}${SUITS[suit]} into position ${position}. Build quickly. The mothership is attacking.`,selectors:[`.suit-button[data-suit="${suit}"]`],labels:[`TAP SUIT ${SUITS[suit]}`]}
]}
function droneTutorialSlides(){const index=state.bomb?.index??0,card=droneCard(index),position=String(droneGlobalPosition(index)).padStart(2,'0'),answerSelector=state.mode==='super'?'.position-code':`.position-button[data-position="${index}"]`;return[
  {title:'MEMORY RAIDERS INCOMING',text:`Read the card displayed on each attacking raider. This raider is carrying ${card[0]}${SUITS[card[1]]}.`,selectors:['.bomb.drone'],labels:[`RAIDER CARD ${card[0]}${SUITS[card[1]]}`]},
  {title:'IDENTIFY ITS POSITION',text:state.mode==='super'?`Use the keypad to enter ${position}, the stack position of ${card[0]}${SUITS[card[1]]}.`:`Tap position ${position}, the stack location of ${card[0]}${SUITS[card[1]]}.`,selectors:[answerSelector],labels:[state.mode==='super'?`TYPE ${position}`:`TAP ${position}`]},
  {title:'TURRETS READY',text:'A correct answer makes the corner turrets track and destroy the raider. Act quickly because raiders fire back near the fortress.',selectors:['.defense-turret.left','.defense-turret.right'],labels:['LEFT TURRET','RIGHT TURRET']}
]}
function activeTutorialSlides(){return state.tutorialKind==='drone'?droneTutorialSlides():buildTutorialSlides()}
function startTutorial(kind='build'){state.paused=true;state.tutorialKind=kind;state.tutorialStep=0;$('tutorial').classList.remove('hidden');renderTutorialStep()}
function renderTutorialStep(){const slides=activeTutorialSlides(),slide=slides[state.tutorialStep],rings=$('tutorialRings');$('targetCard').classList.toggle('tutorial-reveal',state.tutorialKind==='build'&&state.tutorialStep===0);$('tutorialStepLabel').textContent=`HOW TO PLAY · ${state.tutorialStep+1} OF ${slides.length}`;$('tutorialTitle').textContent=slide.title;$('tutorialText').textContent=slide.text;$('tutorialDots').innerHTML=slides.map((_,i)=>`<i class="${i===state.tutorialStep?'active':''}"></i>`).join('');$('tutorialNext').textContent=state.tutorialStep===slides.length-1?(state.tutorialKind==='drone'?'START DEFENSE →':'START MISSION →'):'NEXT →';rings.innerHTML='';requestAnimationFrame(()=>slide.selectors.forEach((selector,index)=>{const target=document.querySelector(selector);if(!target)return;const rect=target.getBoundingClientRect(),ring=document.createElement('i'),pad=7;ring.className='tutorial-ring';if(rect.bottom>window.innerHeight-55)ring.classList.add('label-above');ring.dataset.label=slide.labels[index];ring.style.cssText=`left:${rect.left-pad}px;top:${rect.top-pad}px;width:${rect.width+pad*2}px;height:${rect.height+pad*2}px`;rings.appendChild(ring)}))}
function hasCompletedTutorial(){try{return localStorage.getItem('memory-fortress-tutorial-complete')==='true'}catch{return false}}
function hasCompletedDroneTutorial(){try{return localStorage.getItem('memory-fortress-drone-tutorial-complete')==='true'}catch{return false}}
function beginMission(){$('tutorial').classList.add('hidden');$('tutorialRings').innerHTML='';$('targetCard').classList.remove('tutorial-reveal');state.paused=false;state.buildStartedAt=performance.now();updateUI();flashMessage(`${STACKS[state.stackKey].name} · ${state.mode.toUpperCase()} MODE`,true);scheduleLaser()}
function beginDroneMission(){$('tutorial').classList.add('hidden');$('tutorialRings').innerHTML='';state.paused=false;state.recallStartedAt=performance.now();if(state.bomb){state.bomb.y=-74;state.bomb.spawnedAt=performance.now();state.bomb.el.style.top='-74px'}flashMessage('MEMORY RAIDERS INCOMING',true);state.bombTimer=setInterval(tickBomb,50)}
function finishTutorial(){try{localStorage.setItem(state.tutorialKind==='drone'?'memory-fortress-drone-tutorial-complete':'memory-fortress-tutorial-complete','true')}catch{}if(state.tutorialKind==='drone')beginDroneMission();else beginMission()}

function syncViewportHeight(){const height=window.visualViewport?.height||window.innerHeight;document.documentElement.style.setProperty('--app-height',`${Math.round(height)}px`)}
syncViewportHeight();window.addEventListener('resize',syncViewportHeight);window.visualViewport?.addEventListener('resize',syncViewportHeight);

function cardMarkup(card) {
  const [rank,suit]=card, red=suit==='hearts'||suit==='diamonds';
  return `<div class="card-face ${red?'red':''}"><em>${SUITS[suit]}</em></div><span class="protected-card-index ${red?'red':''}">${rank}<br>${SUITS[suit]}</span>`;
}

function renderFortress() {
  const root=$('fortress'); root.innerHTML='';
  FORTRESS_ROWS.forEach(positions=>{const row=document.createElement('div');row.className='fortress-row';
    positions.forEach(pos=>{const el=document.createElement('div');el.className='fortress-card';el.dataset.position=String(globalPosition(pos)).padStart(2,'0');el.dataset.index=pos;
      if(state.health[pos]>0){el.classList.add('built');el.innerHTML=cardMarkup(sectorCard(pos));if(state.health[pos]<100){const stage=Math.min(4,Math.ceil((100-state.health[pos])/20)),variant=SAFE_DAMAGE_VARIANTS[(globalPosition(pos)*3+pos)%SAFE_DAMAGE_VARIANTS.length];el.classList.add('damaged',`damage-${stage}`,`damage-variant-${variant}`);el.querySelector('.card-face').insertAdjacentHTML('beforeend','<span class="damage-surface"><i class="impact-burn"></i><i class="split main-split"></i><i class="split branch-one"></i><i class="split branch-two"></i><b class="char-patch"></b><em class="ember-seam"></em></span>');if(state.health[pos]<=25){el.classList.add('critical');el.insertAdjacentHTML('beforeend','<span class="card-flames"><i></i><i></i><i></i><b></b><em></em><em></em></span>')}}}
      if(pos===state.built && state.phase===1)el.classList.add('next');
      el.addEventListener('dragover',e=>e.preventDefault());el.addEventListener('drop',e=>{e.preventDefault();placeCard(e.dataTransfer.getData('rank'));});row.appendChild(el)});if(positions.every(pos=>state.health[pos]>0))row.classList.add('completed');root.appendChild(row)});
  if(state.health.every(health=>health>0))root.classList.add('station-complete');
  const field=$('battlefield');field.classList.toggle('danger',state.health.some(health=>health>0&&health<=25));field.classList.toggle('bays-built',state.baysBuilt);field.classList.toggle('turrets-deployed',state.turretsDeployed);$('defenseTurrets').classList.remove('hidden');
}

function renderControls(){
  $('rankRow').innerHTML=RANKS.map(rank=>`<button class="rank-button ${rank===state.selectedRank?'selected':''}" data-rank="${rank}">${rank}</button>`).join('');
  document.querySelectorAll('.rank-button').forEach(b=>b.onclick=()=>{if(state.paused)return;state.selectedRank=b.dataset.rank;renderControls();sound('select')});
  $('suitRow').innerHTML=Object.entries(SUITS).map(([name,symbol])=>`<button class="suit-button ${(name==='hearts'||name==='diamonds')?'red':''}" data-suit="${name}" ${state.selectedRank?'':'disabled'}><span>${symbol}</span><small>${name.toUpperCase()}</small></button>`).join('');
  document.querySelectorAll('.suit-button').forEach(b=>b.onclick=()=>placeCard(b.dataset.suit));
}

function deployMothership(){const ship=$('ship');ship.classList.remove('waiting','hidden','retreating');ship.classList.add('deployed');setTimeout(()=>{if(state.phase!==1||state.built===0)return;state.shipEntered=true;fireLaser()},1800)}

function placeCard(suit){if(state.paused||state.phase!==1||state.built>=13||!state.selectedRank)return;const expected=sectorCard(state.built),chosenRank=state.selectedRank;state.selectedRank=null;
  if(chosenRank===expected[0]&&suit===expected[1]){state.health[state.built]=100;state.built++;if(state.built===1)deployMothership();if(state.built===13){clearTimeout(state.laserTimer);document.querySelectorAll('.laser').forEach(laser=>laser.remove())}state.score+=100*state.combo;state.combo=Math.min(9,state.combo+1);flashMessage(`${chosenRank} OF ${suit.toUpperCase()} · SECURED`,true);updateUI();renderFortress();renderControls();if(state.built<13)sound('build');
    if(state.built===13)showPhaseComplete();
  }else{state.combo=1;state.score=Math.max(0,state.score-25);flashMessage('MEMORY MISMATCH',false);updateUI();renderControls();sound('error')}
}

function fireLaser(){if(state.paused||state.phase!==1||state.built===0||state.built>=13||!state.shipEntered)return;
  // Attack the newest wall segment so a destroyed card becomes the next card to rebuild.
  const target=state.built-1,card=document.querySelector(`[data-index="${target}"]`);if(!card)return;
  const field=$('battlefield').getBoundingClientRect(),cannons=[...document.querySelectorAll('.ship-cannon')],cannon=cannons[state.cannonIndex++%cannons.length].getBoundingClientRect(),rect=card.getBoundingClientRect(),startX=cannon.left-field.left+cannon.width/2,startY=cannon.bottom-field.top-2,endX=rect.left-field.left+rect.width/2,endY=rect.top-field.top+rect.height/2,dx=endX-startX,dy=endY-startY,length=Math.hypot(dx,dy),angle=Math.atan2(dy,dx)*180/Math.PI;const laser=document.createElement('i');laser.className='laser';laser.style.left=`${startX}px`;laser.style.top=`${startY}px`;laser.style.width=`${length}px`;laser.style.transform=`rotate(${angle}deg) scaleX(0)`;$('laserLayer').appendChild(laser);
  sound('laser');
  requestAnimationFrame(()=>requestAnimationFrame(()=>{laser.style.transform=`rotate(${angle}deg) scaleX(1)`}));
  setTimeout(()=>{laser.remove();if(state.built>=13||state.phase!==1)return;damageCard(target,15);const impact=document.createElement('i');impact.className='impact';impact.style.left=`${rect.left-field.left+rect.width/2-14}px`;impact.style.top=`${rect.top-field.top+rect.height/2-14}px`;$('laserLayer').appendChild(impact);setTimeout(()=>impact.remove(),400)},430)
}

function damageCard(index,amount){if(state.phase!==1||state.paused)return;triggerDamageAlarm();state.health[index]=Math.max(0,state.health[index]-amount);state.damagePenalty+=100;state.score=Math.max(0,state.score-100);showPointPenalty(100,'MOTHERSHIP HIT');sound('impact');const destroyed=state.health[index]===0;if(destroyed){explodeCard(index);state.built=Math.max(0,state.built-1);state.combo=1;flashMessage(`POSITION ${String(globalPosition(index)).padStart(2,'0')} DESTROYED · −100 POINTS`,false);sound('breach')}else if(state.health[index]<=25){flashMessage(`POSITION ${String(globalPosition(index)).padStart(2,'0')} CRITICAL · −100 POINTS`,false);sound('burn')}else{flashMessage(`POSITION ${String(globalPosition(index)).padStart(2,'0')} HIT · −100 POINTS`,false)}renderFortress();updateUI();if(destroyed&&state.built===0)showDefeat('FORTRESS DESTROYED')}
function triggerDamageAlarm(){const shell=document.querySelector('.app-shell'),field=$('battlefield');shell.classList.remove('damage-alarm');field.classList.remove('battle-shake');void shell.offsetWidth;shell.classList.add('damage-alarm');field.classList.add('battle-shake');setTimeout(()=>{shell.classList.remove('damage-alarm');field.classList.remove('battle-shake')},620)}
function scheduleLaser(){clearTimeout(state.laserTimer);if(state.phase!==1)return;const burst=Math.random()<.18,delay=burst?450+Math.random()*300:1400+Math.random()*1200;state.laserTimer=setTimeout(()=>{fireLaser();scheduleLaser()},delay)}
function explodeCard(index){const card=document.querySelector(`[data-index="${index}"]`),field=$('battlefield').getBoundingClientRect();if(!card)return;const rect=card.getBoundingClientRect(),blast=document.createElement('span');blast.className='card-explosion';blast.style.left=`${rect.left-field.left+rect.width/2}px`;blast.style.top=`${rect.top-field.top+rect.height/2}px`;blast.innerHTML='<b></b><em></em>'+Array.from({length:16},(_,i)=>{const angle=Math.PI*2*i/16,distance=28+Math.random()*44;return `<i style="--dx:${Math.cos(angle)*distance}px;--dy:${Math.sin(angle)*distance}px;--rot:${Math.round(Math.random()*360)}deg;--delay:${Math.random()*.08}s"></i>`}).join('');$('laserLayer').appendChild(blast);setTimeout(()=>blast.remove(),900)}

function showPhaseComplete(){if(state.built!==13||state.ending)return;clearTimeout(state.laserTimer);finishBuildTimer();showBuildScoreSequence(()=>{state.turretsDeployed=true;renderFortress();sound('deploy');setTimeout(()=>$('battlefield').classList.add('turret-hero'),3500);setTimeout(showFortressReadyModal,4500)})}
function showFortressReadyModal(){$('leaderboard').classList.add('hidden');$('replayOption').classList.add('hidden');$('modal').classList.remove('hidden');$('modalEyebrow').textContent=`SECTOR ${String(state.sector+1).padStart(2,'0')} · FORTRESS COMPLETE`;$('modalTitle').textContent='FORTRESS ONLINE';$('modalText').textContent=state.mode==='super'?'Your 13 shuffled fortress positions are secure. Now intercept a different set of 13 cards from the raider deck.':`Positions ${globalPosition(0)}–${globalPosition(12)} are secure. Now recall all 13 cards.`;$('modalButton').textContent='BEGIN RECALL';$('modalButton').onclick=startPhaseTwo}
function shuffle(values){for(let i=values.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[values[i],values[j]]=[values[j],values[i]]}return values}
function startPhaseTwo(){$('modal').classList.add('hidden');state.paused=false;state.ending=false;state.shipEntered=false;const ship=$('ship');ship.classList.add('retreating');setTimeout(()=>ship.classList.add('hidden'),900);state.phase=2;state.phaseTwoHits=0;state.combo=1;state.recallStartScore=state.score;state.recallStartedAt=null;state.recallElapsed=null;state.recallTimeBonus=0;state.droneDestroyed=0;state.bomb=null;state.positionEntry='';state.recallQueue=shuffle(Array.from({length:13},(_,i)=>i));state.reviewQueue=[];state.mastered=new Set();state.misses=0;state.eliteRaiderIndex=chooseEliteRaider();state.eliteRaiderSpawned=false;$('battleMessage').textContent='IDENTIFY THE FALLING CARD';$('buildControls').classList.add('hidden');$('phaseTwoControls').classList.remove('hidden');$('defenseTurrets').classList.remove('hidden');if(state.mode==='super'){renderPositionKeypad()}else{$('positionGrid').classList.remove('numeric-keypad');$('positionGrid').innerHTML=Array.from({length:13},(_,i)=>`<button class="position-button" data-position="${i}">${String(globalPosition(i)).padStart(2,'0')}</button>`).join('');document.querySelectorAll('.position-button').forEach(b=>b.onclick=()=>intercept(Number(b.dataset.position)))}updateUI();spawnBomb();if(hasCompletedDroneTutorial()&&!state.forceTutorial){state.recallStartedAt=performance.now();state.bombTimer=setInterval(tickBomb,50)}else if(state.bomb){const previewY=Math.min(180,$('battlefield').clientHeight*.45);state.bomb.y=previewY;state.bomb.el.style.top=`${previewY}px`;startTutorial('drone')}}
function renderPositionKeypad(){$('positionGrid').classList.add('numeric-keypad');$('positionGrid').innerHTML=`<div class="position-code"><small>ENTER POSITION 01–52</small><strong id="positionEntry">${state.positionEntry.padEnd(2,'–')}</strong></div>${[1,2,3,4,5,6,7,8,9,'CLR',0,'BACK'].map(value=>`<button class="position-button" data-digit="${value}">${value==='BACK'?'⌫':value}</button>`).join('')}`;document.querySelectorAll('[data-digit]').forEach(button=>button.onclick=()=>inputPositionDigit(button.dataset.digit))}
function inputPositionDigit(digit){if(state.paused||!state.bomb||state.bomb.engaged)return;if(digit==='CLR'){state.positionEntry='';renderPositionKeypad();return}if(digit==='BACK'){state.positionEntry=state.positionEntry.slice(0,-1);renderPositionKeypad();return}if(state.positionEntry.length>=2)return;state.positionEntry+=digit;renderPositionKeypad();if(state.positionEntry.length===2){const answer=Number(state.positionEntry);state.positionEntry='';setTimeout(()=>{if(answer>=1&&answer<=52)intercept(answer);renderPositionKeypad()},140)}}
function nextRecallCard(){if(!state.recallQueue.length&&state.reviewQueue.length){state.recallQueue=shuffle([...new Set(state.reviewQueue)].filter(i=>!state.mastered.has(i)));state.reviewQueue=[];flashMessage('REVIEW ROUND',true)}while(state.recallQueue.length&&state.mastered.has(state.recallQueue[0]))state.recallQueue.shift();return state.recallQueue.shift()}
function spawnBomb(){if(state.paused||state.bomb)return;if(state.mastered.size===13){showVictory();return}const index=nextRecallCard();if(index===undefined)return;const el=document.createElement('div'),card=droneCard(index),fieldWidth=$('battlefield').clientWidth,baseX=58+Math.random()*Math.max(1,fieldWidth-154),red=card[1]==='hearts'||card[1]==='diamonds',elite=index===state.eliteRaiderIndex&&!state.eliteRaiderSpawned;if(elite)state.eliteRaiderSpawned=true;el.className=`bomb drone${elite?' elite-raider':''}`;el.innerHTML=`<i class="drone-wing left"></i><i class="drone-wing right"></i><span class="drone-eye left"></span><span class="drone-eye right"></span><div class="drone-core"><b class="${red?'red':''}">${card[0]}<span>${SUITS[card[1]]}</span></b></div><span class="drone-thruster"></span>`;el.style.left=`${baseX}px`;$('bombLayer').appendChild(el);state.bomb={index,el,elite,y:-74,baseX,amplitude:76+Math.random()*38,phase:Math.random()*Math.PI*2,zigzagSpeed:.0456+Math.random()*.0316,descentMultiplier:elite?1.5:1,spawnedAt:performance.now(),missed:false,fired:false,fireAt:null,aiming:false,aimX:null};if(elite)showEliteWarning();updateUI()}
function markMissed(index){if(!state.mastered.has(index)&&!state.reviewQueue.includes(index))state.reviewQueue.push(index);state.misses++;state.combo=1}
function tickBomb(){if(state.paused)return;if(!state.bomb){spawnBomb();return}const field=$('battlefield'),drone=state.bomb,now=performance.now();drone.y+=Math.max(1.05,field.clientHeight/15000*50)*drone.descentMultiplier;drone.phase+=drone.zigzagSpeed;const sweepX=drone.baseX+Math.sin(drone.phase)*drone.amplitude,freeX=Math.max(3,Math.min(field.clientWidth-drone.el.offsetWidth-3,sweepX)),x=drone.aiming?drone.aimX:freeX,bank=Math.max(-20,Math.min(20,Math.cos(drone.phase)*-14)),visualBank=drone.aiming?0:bank;drone.el.style.top=`${drone.y}px`;drone.el.style.left=`${x}px`;drone.el.style.transform=`rotate(${visualBank}deg)`;drone.el.style.setProperty('--wing-bank',`${bank}deg`);drone.el.style.setProperty('--trail-lean',`${Math.max(-18,Math.min(18,-bank))}deg`);trackTurrets(drone.el);const floor=field.clientHeight-drone.el.offsetHeight-10;if(!drone.engaged&&!drone.fired&&drone.y>=floor*.5&&drone.fireAt===null)drone.fireAt=now+Math.random()*1800;if(!drone.engaged&&!drone.fired&&!drone.aiming&&drone.fireAt!==null&&now>=drone.fireAt){drone.aiming=true;drone.aimX=x;drone.fireAt=now+360;drone.el.classList.add('aiming')}if(!drone.engaged&&!drone.fired&&drone.aiming&&now>=drone.fireAt){drone.fired=true;drone.el.classList.remove('aiming');fireDroneLaser(drone)}if(!drone.engaged&&drone.y>floor)crashDrone(drone,floor)}
function crashDrone(drone,floor){drone.engaged=true;drone.y=floor;drone.el.style.top=`${floor}px`;drone.el.classList.remove('aiming');drone.el.classList.add('crashing');markMissed(drone.index);recordRaiderResult(drone.index,(performance.now()-drone.spawnedAt)/1000,true);const impact=drone.el.getBoundingClientRect(),impactX=impact.left+impact.width/2,impactY=impact.bottom,surviving=state.health.map((health,index)=>({health,index,el:document.querySelector(`[data-index="${index}"]`)})).filter(card=>card.health>0&&card.el).map(card=>{const rect=card.el.getBoundingClientRect();return {...card,distance:Math.hypot(rect.left+rect.width/2-impactX,rect.top+rect.height/2-impactY)}}).sort((a,b)=>a.distance-b.distance),damageCount=1+Math.floor(Math.random()*3),targets=surviving.slice(0,damageCount).map(card=>card.index),count=targets.length,penalty=count*500;explodeDrone(drone.el);triggerDamageAlarm();targets.forEach(index=>{state.health[index]=0;explodeCard(index)});state.droneDestroyed+=count;state.damagePenalty+=penalty;state.score=Math.max(0,state.score-penalty);showPointPenalty(penalty,`DRONE CRASH · ${count} NEAREST CARD${count===1?'':'S'} DESTROYED`);flashMessage(`DRONE CRASH · ${count} NEAREST CARD${count===1?'':'S'} DESTROYED`,false);sound('breach');drone.el.remove();state.bomb=null;renderFortress();updateUI();if(state.droneDestroyed>=3||!state.health.some(Boolean)){state.paused=true;const reason=state.droneDestroyed>=3?'3 CARDS DESTROYED':'FORTRESS DESTROYED';setTimeout(()=>{state.paused=false;showDefeat(reason)},1500)}else setTimeout(spawnBomb,700)}
function trackTurrets(droneEl){const target=droneEl.getBoundingClientRect();document.querySelectorAll('.turret-head').forEach(head=>{const rect=head.getBoundingClientRect(),dx=target.left+target.width/2-(rect.left+rect.width/2),dy=target.top+target.height/2-(rect.top+rect.height/2),angle=Math.atan2(dy,dx)*180/Math.PI;head.style.transform=`rotate(${angle+90}deg)`})}
function fireDroneLaser(drone){const surviving=state.health.map((health,index)=>({health,index})).filter(card=>card.health>0);if(!surviving.length)return;const lowestHealth=Math.min(...surviving.map(card=>card.health)),weakest=surviving.filter(card=>card.health===lowestHealth),target=weakest[Math.floor(Math.random()*weakest.length)].index,card=document.querySelector(`[data-index="${target}"]`),field=$('battlefield').getBoundingClientRect(),source=drone.el.querySelector('.drone-core').getBoundingClientRect(),rect=card?.getBoundingClientRect();if(!rect)return;const startX=source.left-field.left+source.width/2,startY=source.top-field.top+source.height/2,endX=rect.left-field.left+rect.width/2,endY=rect.top-field.top+rect.height/2,dx=endX-startX,dy=endY-startY,length=Math.hypot(dx,dy),angle=Math.atan2(dy,dx)*180/Math.PI,beam=document.createElement('i');beam.className='drone-laser';beam.style.cssText=`left:${startX}px;top:${startY}px;width:${length}px;transform:rotate(${angle}deg) scaleX(0)`;$('laserLayer').appendChild(beam);sound('enemyLaser');requestAnimationFrame(()=>requestAnimationFrame(()=>beam.style.transform=`rotate(${angle}deg) scaleX(1)`));setTimeout(()=>{beam.remove();hitFortressFromDrone(target)},340)}
function hitFortressFromDrone(index){if(state.phase!==2||state.paused||state.health[index]<=0)return;triggerDamageAlarm();state.health[index]=Math.max(0,state.health[index]-35);state.damagePenalty+=500;state.score=Math.max(0,state.score-500);showPointPenalty(500,'RAIDER HIT');const destroyed=state.health[index]===0;if(destroyed){state.droneDestroyed++;explodeCard(index);flashMessage(`POSITION ${String(globalPosition(index)).padStart(2,'0')} DESTROYED · −500 POINTS`,false);sound('breach')}else{flashMessage(`POSITION ${String(globalPosition(index)).padStart(2,'0')} HIT · −500 POINTS`,false);sound('impact')}renderFortress();updateUI();if(state.droneDestroyed>=3)showDefeat('3 CARDS DESTROYED')}
function showPointPenalty(points,label='ENEMY HIT'){document.querySelectorAll('.point-penalty').forEach(alert=>alert.remove());const field=$('battlefield').getBoundingClientRect(),popup=document.createElement('strong');popup.className='point-penalty';popup.innerHTML=`<b>${label}</b>−${points} POINTS`;popup.style.left=`${field.width/2}px`;popup.style.top=`${field.height*.44}px`;$('laserLayer').appendChild(popup);setTimeout(()=>popup.remove(),1450)}
function showPhaseScore(label,onComplete){state.paused=true;document.querySelectorAll('.point-penalty').forEach(alert=>alert.remove());const field=$('battlefield').getBoundingClientRect(),popup=document.createElement('strong'),isTurretScore=label.startsWith('DEFENSIVE TURRETS'),displayTime=isTurretScore?5000:4000,scoreText=`${state.score.toLocaleString()} POINTS`;popup.className=`point-penalty phase-score-token${isTurretScore?' turret-score-token':''}`;popup.innerHTML=isTurretScore?`<b>${label}<em>${scoreText}</em></b>`:`<b>${label}</b>${scoreText}`;popup.style.left=`${field.width/2}px`;popup.style.top=`${field.height*.44}px`;popup.style.setProperty('--score-hold',`${displayTime-50}ms`);$('laserLayer').appendChild(popup);sound('victory');setTimeout(()=>{popup.remove();onComplete()},displayTime)}
function animateScoreRoll(element,from,to,duration=1250){const start=performance.now(),tick=now=>{const progress=Math.min(1,(now-start)/duration),eased=1-Math.pow(1-progress,3),value=Math.round(from+(to-from)*eased);element.textContent=value.toLocaleString();if(progress<1)requestAnimationFrame(tick)};requestAnimationFrame(tick)}
function showBuildScoreSequence(onComplete){state.paused=true;document.querySelectorAll('.point-penalty').forEach(alert=>alert.remove());const field=$('battlefield').getBoundingClientRect(),popup=document.createElement('strong'),sectorTotal=state.score-state.sectorStartScore,buildScore=sectorTotal-state.timeBonus,displayTime=6600;popup.className='point-penalty phase-score-token turret-score-token pinball-score-token';popup.innerHTML=`<b>DEFENSIVE TURRETS<br>NOW ONLINE<span class="pinball-line build-line"><small>BUILD SCORE · ${formatTime(state.buildElapsed)}</small><strong>${buildScore.toLocaleString()}</strong></span><span class="pinball-line bonus-line"><small>TIME BONUS</small><strong>+${state.timeBonus.toLocaleString()}</strong></span><em class="pinball-total"><small>SECTOR TOTAL</small><strong>${buildScore.toLocaleString()}</strong></em></b>`;popup.style.left=`${field.width/2}px`;popup.style.top=`${field.height*.4}px`;popup.style.setProperty('--score-hold',`${displayTime-50}ms`);$('laserLayer').appendChild(popup);sound('victory');setTimeout(()=>{popup.classList.add('show-bonus');sound('build')},1100);setTimeout(()=>{popup.classList.add('tallying');animateScoreRoll(popup.querySelector('.pinball-total strong'),buildScore,sectorTotal)},2200);setTimeout(()=>popup.classList.add('total-settled'),3500);setTimeout(()=>{popup.remove();onComplete()},displayTime)}
function showRaiderScoreSequence(onComplete){state.paused=true;document.querySelectorAll('.point-penalty').forEach(alert=>alert.remove());const field=$('battlefield').getBoundingClientRect(),popup=document.createElement('strong'),sectorTotal=state.score-state.sectorStartScore,raiderScore=state.score-state.recallStartScore-state.recallTimeBonus,totalBeforeBonus=sectorTotal-state.recallTimeBonus,displayTime=6600;popup.className='point-penalty phase-score-token turret-score-token pinball-score-token raider-score-token';popup.innerHTML=`<b>RAIDER DEFENSE COMPLETE<span class="pinball-line build-line"><small>RAIDER DEFENSE SCORE · ${formatTime(state.recallElapsed)}</small><strong>${raiderScore.toLocaleString()}</strong></span><span class="pinball-line bonus-line"><small>TIME BONUS</small><strong>+${state.recallTimeBonus.toLocaleString()}</strong></span><em class="pinball-total"><small>SECTOR TOTAL</small><strong>${totalBeforeBonus.toLocaleString()}</strong></em></b>`;popup.style.left=`${field.width/2}px`;popup.style.top=`${field.height*.4}px`;popup.style.setProperty('--score-hold',`${displayTime-50}ms`);$('laserLayer').appendChild(popup);sound('victory');setTimeout(()=>{popup.classList.add('show-bonus');sound('build')},1100);setTimeout(()=>{popup.classList.add('tallying');animateScoreRoll(popup.querySelector('.pinball-total strong'),totalBeforeBonus,sectorTotal)},2200);setTimeout(()=>popup.classList.add('total-settled'),3500);setTimeout(()=>{popup.remove();onComplete()},displayTime)}
function showDefeat(reason){if(state.ending)return;if(state.phase===1&&state.buildStartedAt)state.buildElapsed=(performance.now()-state.buildStartedAt)/1000;if(state.phase===2&&state.recallStartedAt)state.recallElapsed=(performance.now()-state.recallStartedAt)/1000;state.ending=true;state.paused=true;clearTimeout(state.laserTimer);clearInterval(state.bombTimer);state.bomb?.el.remove();state.bomb=null;document.querySelectorAll('.point-penalty').forEach(alert=>alert.remove());const field=$('battlefield').getBoundingClientRect(),popup=document.createElement('strong');popup.className='point-penalty defeat-token';popup.innerHTML=`<b>${reason}</b>GAME OVER<small>${randomDefeatTaunt()}</small>`;popup.style.left=`${field.width/2}px`;popup.style.top=`${Math.max(64,field.height*.2)}px`;$('laserLayer').appendChild(popup);sound('breach');setTimeout(()=>{popup.remove();showDefeatScore(reason)},5000)}
function showDefeatScore(reason){const scores=getHighScores();$('replayOption').classList.add('hidden');$('modal').classList.remove('hidden');$('leaderboard').classList.remove('hidden');$('modalEyebrow').textContent='MISSION FAILED';$('modalTitle').textContent='SCORING REPORT';$('modalText').textContent=`${reason}. Your remaining score has been preserved, but this attempt was not added to the completed-mission leaderboard.`;document.querySelector('.run-score span').textContent='SCORE REMAINING';$('runScore').textContent=String(state.score).padStart(4,'0');$('runTimes').textContent=sectorTimesText();$('scoreResult').textContent='DEFEAT · NOT RECORDED';$('leaderboardList').innerHTML=scores.length?scores.map((entry,i)=>`<li><b>${i+1}</b><strong>${String(entry.score).padStart(4,'0')}</strong><span>${Number.isFinite(entry.buildTime)?`BUILD ${formatTime(entry.buildTime)}<br>RAIDERS ${formatTime(entry.recallTime)}`:'TIME NOT RECORDED'}</span></li>`).join(''):'<li><b>-</b><strong>NO COMPLETED RUNS</strong><span>YET</span></li>';$('modalButton').textContent='RETRY THIS SECTOR';$('modalButton').onclick=retrySector}
function raiderInterceptReward(raider){const field=$('battlefield'),floor=field.clientHeight-raider.el.offsetHeight-10,progress=Math.max(0,Math.min(1,(raider.y+74)/(floor+74)));if(progress<4/15)return 200;if(progress<8/15)return 150;if(progress<12/15)return 100;return 75}
function showRaiderReward(raiderEl,reward){if(!raiderEl?.isConnected)return;const field=$('battlefield').getBoundingClientRect(),rect=raiderEl.getBoundingClientRect(),popup=document.createElement('strong');popup.className='raider-reward';popup.textContent=`+${reward}`;popup.style.left=`${rect.left-field.left+rect.width/2}px`;popup.style.top=`${rect.top-field.top+rect.height/2}px`;$('laserLayer').appendChild(popup);setTimeout(()=>popup.remove(),950)}
function showEliteWarning(){document.querySelectorAll('.elite-warning').forEach(alert=>alert.remove());const field=$('battlefield').getBoundingClientRect(),warning=document.createElement('strong'),shell=document.querySelector('.app-shell');warning.className='elite-warning';warning.textContent='ELITE RAIDER INCOMING';warning.style.left=`${field.width/2}px`;warning.style.top=`${Math.max(58,field.height*.24)}px`;$('laserLayer').appendChild(warning);shell.classList.remove('elite-alarm');void shell.offsetWidth;shell.classList.add('elite-alarm');sound('eliteAlarm');setTimeout(()=>{warning.remove();shell.classList.remove('elite-alarm')},1850)}
function showMissPenalty(){document.querySelectorAll('.miss-penalty').forEach(alert=>alert.remove());const field=$('battlefield').getBoundingClientRect(),popup=document.createElement('strong'),shell=document.querySelector('.app-shell');popup.className='miss-penalty';popup.innerHTML='<b>MISS</b>−50';popup.style.left=`${field.width/2}px`;popup.style.top=`${Math.max(48,field.height*.18)}px`;$('laserLayer').appendChild(popup);shell.classList.remove('miss-alarm');void shell.offsetWidth;shell.classList.add('miss-alarm');setTimeout(()=>shell.classList.remove('miss-alarm'),360);setTimeout(()=>popup.remove(),1150)}
function intercept(position){if(state.paused||!state.bomb||state.bomb.engaged)return;const expected=state.mode==='super'?droneGlobalPosition(state.bomb.index):state.bomb.index;if(position===expected){const masteredIndex=state.bomb.index,reward=raiderInterceptReward(state.bomb)*(state.bomb.elite?2:1),raiderEl=state.bomb.el;recordRaiderResult(masteredIndex,(performance.now()-state.bomb.spawnedAt)/1000,state.bomb.missed);state.bomb.engaged=true;state.score+=reward*state.combo;state.combo=Math.min(9,state.combo+1);state.mastered.add(masteredIndex);state.reviewQueue=state.reviewQueue.filter(i=>i!==masteredIndex);state.phaseTwoHits=state.mastered.size;raiderEl.classList.add('targeted');flashMessage(`${state.bomb.elite?'ELITE RAIDER DESTROYED':'GROUND DEFENSE LOCK'} · +${reward}`,true);setTimeout(()=>showRaiderReward(raiderEl,reward),350);shootDownDrone(()=>{state.bomb=null;if(state.mastered.size===13)showVictory();else spawnBomb()})}else{if(!state.bomb.missed){state.bomb.missed=true;markMissed(state.bomb.index)}state.score=Math.max(0,state.score-50);showMissPenalty();flashMessage('WRONG · CARD QUEUED FOR REVIEW',false);sound('error')}updateUI()}
function shootDownDrone(onComplete){const field=$('battlefield').getBoundingClientRect(),droneEl=state.bomb.el,rect=droneEl.getBoundingClientRect(),heads=[...document.querySelectorAll('.turret-head')],targetX=rect.left+rect.width/2,targetY=rect.top+rect.height/2,head=heads.sort((a,b)=>{const ar=a.getBoundingClientRect(),br=b.getBoundingClientRect();return Math.hypot(targetX-ar.left-ar.width/2,targetY-ar.top-ar.height/2)-Math.hypot(targetX-br.left-br.width/2,targetY-br.top-br.height/2)})[0],source=head.getBoundingClientRect(),centerX=source.left+source.width/2,centerY=source.top+source.height/2,worldDx=targetX-centerX,worldDy=targetY-centerY,worldLength=Math.hypot(worldDx,worldDy),forwardX=worldDx/worldLength,forwardY=worldDy/worldLength,sideX=-forwardY,sideY=forwardX,shots=[-7,7].map(offset=>{const startWorldX=centerX+forwardX*9+sideX*offset,startWorldY=centerY+forwardY*9+sideY*offset,startX=startWorldX-field.left,startY=startWorldY-field.top,endX=targetX-field.left,endY=targetY-field.top,dx=endX-startX,dy=endY-startY,length=Math.hypot(dx,dy),angle=Math.atan2(dy,dx)*180/Math.PI,beam=document.createElement('i'),muzzle=document.createElement('i');beam.className='ground-laser twin-beam';beam.style.cssText=`left:${startX}px;top:${startY}px;width:${length}px;transform:rotate(${angle}deg) scaleX(0)`;muzzle.className='ground-muzzle';muzzle.style.left=`${startX}px`;muzzle.style.top=`${startY}px`;$('laserLayer').append(muzzle,beam);return {beam,muzzle}});head.closest('.defense-turret').classList.add('firing');sound('groundLaser');requestAnimationFrame(()=>requestAnimationFrame(()=>shots.forEach(({beam})=>beam.style.transform=beam.style.transform.replace('scaleX(0)','scaleX(1)'))));setTimeout(()=>{shots.forEach(({beam,muzzle})=>{beam.remove();muzzle.remove()});head.closest('.defense-turret').classList.remove('firing');explodeDrone(droneEl);droneEl.remove();sound('droneBlast');setTimeout(onComplete,260)},390)}
function explodeDrone(droneEl){const field=$('battlefield').getBoundingClientRect(),rect=droneEl.getBoundingClientRect(),blast=document.createElement('span');blast.className='drone-explosion';blast.style.left=`${rect.left-field.left+rect.width/2}px`;blast.style.top=`${rect.top-field.top+rect.height/2}px`;blast.innerHTML='<b></b><em></em>'+Array.from({length:18},(_,i)=>{const angle=Math.PI*2*i/18,distance=35+Math.random()*55;return `<i style="--dx:${Math.cos(angle)*distance}px;--dy:${Math.sin(angle)*distance}px;--rot:${Math.round(Math.random()*540)}deg;--delay:${Math.random()*.07}s"></i>`}).join('');$('laserLayer').appendChild(blast);setTimeout(()=>blast.remove(),1050)}
function showVictory(){clearInterval(state.bombTimer);state.bomb?.el.remove();state.bomb=null;finishRecallTimer();showRaiderScoreSequence(()=>showLeaderboard(state.sector===SECTOR_COUNT-1))}
function leaderboardKey(){return `memory-fortress-${state.stackKey}-${state.mode}-sector-${state.sector+1}-scores`}
function getHighScores(){try{return JSON.parse(localStorage.getItem(leaderboardKey())||'[]').filter(x=>Number.isFinite(x.score)).sort((a,b)=>b.score-a.score).slice(0,3)}catch{return[]}}
function showLeaderboard(finalSector){const sectorScore=state.score-state.sectorStartScore,previous=getHighScores(),previousBest=previous[0]?.score??-1,qualifies=previous.length<3||sectorScore>previous[previous.length-1].score,isNumberOne=sectorScore>previousBest,beatPrevious=isNumberOne&&previousBest>=0;let scores=previous;if(qualifies){scores=[...previous,{score:sectorScore,date:new Date().toISOString(),buildTime:state.buildElapsed,recallTime:state.recallElapsed}].sort((a,b)=>b.score-a.score).slice(0,3);try{localStorage.setItem(leaderboardKey(),JSON.stringify(scores))}catch{}}
  $('replayOption').classList.toggle('hidden',finalSector);$('replaySectorButton').textContent=`REPLAY SECTOR ${state.sector+1}`;$('replaySectorButton').onclick=replayCompletedSector;
  document.querySelector('.run-score span').textContent='THIS RUN';$('modal').classList.remove('hidden');$('leaderboard').classList.remove('hidden');$('modalEyebrow').textContent=isNumberOne?(beatPrevious?'YOU BEAT YOUR BEST!':'FIRST SECTOR RECORD'):`SECTOR ${String(state.sector+1).padStart(2,'0')} COMPLETE`;$('modalTitle').textContent=isNumberOne?'NEW HIGH SCORE!':'SECTOR LEADERBOARD';$('modalText').textContent=`${STACKS[state.stackKey].name} ${sectorDescription()} mastered${state.misses?` with ${state.misses} reviewed miss${state.misses===1?'':'es'}`:' with a perfect recall'}${state.damagePenalty?` · ${state.damagePenalty} damage points lost`:''}!`;$('runScore').textContent=String(sectorScore).padStart(4,'0');$('runTimes').textContent=sectorTimesText();$('scoreResult').textContent=isNumberOne?(beatPrevious?'#1 · BETTER THAN EVER!':'#1 · FIRST RECORD'):qualifies?'TOP 3 · RECORDED':'THIS RUN · NOT RECORDED';$('leaderboardList').innerHTML=scores.map((entry,i)=>`<li class="${entry.score===sectorScore&&qualifies?'current':''}"><b>${i+1}</b><strong>${String(entry.score).padStart(4,'0')}</strong><span>${Number.isFinite(entry.buildTime)?`BUILD ${formatTime(entry.buildTime)}<br>RAIDERS ${formatTime(entry.recallTime)}`:'TIME NOT RECORDED'}</span></li>`).join('');$('modalButton').textContent=finalSector?'FULL DECK COMPLETE · PLAY AGAIN':state.mode==='super'?`CONTINUE TO SECTOR ${state.sector+2}`:`CONTINUE TO ${globalPosition(12)+1}–${globalPosition(12)+13}`;$('modalButton').onclick=finalSector?restart:startNextSector;if(isNumberOne){sound('highscore');launchFireworks()}else sound('victory')}
function launchFireworks(){const layer=$('fireworksLayer'),colors=['#ff3b1f','#ff761a','#ffc928','#ff5138'];layer.innerHTML='';layer.classList.add('active');for(let burst=0;burst<8;burst++){setTimeout(()=>{const x=12+Math.random()*76,y=12+Math.random()*55;for(let i=0;i<18;i++){const spark=document.createElement('i'),angle=Math.PI*2*i/18,distance=45+Math.random()*75;spark.style.cssText=`--x:${x}vw;--y:${y}vh;--dx:${Math.cos(angle)*distance}px;--dy:${Math.sin(angle)*distance}px;--color:${colors[Math.floor(Math.random()*colors.length)]};--delay:${Math.random()*.08}s`;layer.appendChild(spark);setTimeout(()=>spark.remove(),1100)}sound('pop')},burst*230)}setTimeout(()=>{layer.classList.remove('active');layer.innerHTML=''},3000)}
function resetMothership(){state.shipEntered=false;state.cannonIndex=Math.floor(Math.random()*3);$('battlefield').classList.remove('turret-hero');$('ship').classList.remove('hidden','retreating','deployed');$('ship').classList.add('waiting')}
function startNextSector(){state.sector++;state.sectorStartScore=state.score;state.recallStartScore=state.score;state.phase=1;state.paused=false;state.ending=false;state.built=0;state.baysBuilt=true;state.turretsDeployed=false;state.health=Array(13).fill(0);state.selectedRank=null;state.combo=1;state.bomb=null;state.phaseTwoHits=0;state.droneDestroyed=0;state.mastered=new Set();state.misses=0;state.damagePenalty=0;state.buildStartedAt=performance.now();state.buildElapsed=null;state.recallStartedAt=null;state.recallElapsed=null;state.timeBonus=0;state.recallTimeBonus=0;resetMothership();$('modal').classList.add('hidden');$('phaseTwoControls').classList.add('hidden');$('buildControls').classList.remove('hidden');renderFortress();renderControls();updateUI();flashMessage(`SECTOR ${state.sector+1} · BUILD POSITION ${globalPosition(0)}`,true);scheduleLaser()}
function retrySector(){state.score=0;state.sectorStartScore=0;state.recallStartScore=0;state.phase=1;state.paused=false;state.ending=false;state.built=0;state.baysBuilt=true;state.turretsDeployed=false;state.health=Array(13).fill(0);state.selectedRank=null;state.combo=1;state.bomb=null;state.phaseTwoHits=0;state.droneDestroyed=0;state.mastered=new Set();state.misses=0;state.damagePenalty=0;state.buildStartedAt=performance.now();state.buildElapsed=null;state.recallStartedAt=null;state.recallElapsed=null;state.timeBonus=0;state.recallTimeBonus=0;$('bombLayer').innerHTML='';resetMothership();$('modal').classList.add('hidden');$('phaseTwoControls').classList.add('hidden');$('buildControls').classList.remove('hidden');renderFortress();renderControls();updateUI();flashMessage(`RETRY SECTOR ${state.sector+1} · POSITION ${globalPosition(0)}`,true);scheduleLaser()}
function replayCompletedSector(){state.score=state.sectorStartScore;retrySector()}
function flashMessage(text,good){const el=$('battleMessage');el.textContent=text;el.style.color=good?'var(--cyan)':'var(--danger)';clearTimeout(el._timer);el._timer=setTimeout(()=>{el.textContent=state.phase===1?`FORTIFY POSITION ${String(globalPosition(state.built)).padStart(2,'0')}`:'IDENTIFY THE FALLING CARD';el.style.color='var(--cyan)'},900)}
function updateUI(){const sectorNumber=String(state.sector+1).padStart(2,'0'),stackName=state.stackKey?STACKS[state.stackKey].name:'SELECT STACK';$('sectorLabel').textContent=`${stackName} // SECTOR ${sectorNumber} // ${sectorDescription()}`;$('phaseLabel').textContent=`${sectorNumber} · ${state.phase===1?'BUILD':'RECALL'}`;$('scoreLabel').textContent=String(state.score).padStart(4,'0');$('comboLabel').textContent=`×${state.combo}`;$('progressText').textContent=state.phase===1?`${state.built} / 13 BUILT`:`${state.phaseTwoHits} / 13 MASTERED`;$('progressBar').style.width=`${state.phase===1?state.built/13*100:state.phaseTwoHits/13*100}%`;if(state.phase===2&&$('recallStatus'))$('recallStatus').textContent=String(13-state.mastered.size);
  $('targetCard').classList.toggle('answer-hidden',state.mode!=='training');if(state.built<13){$('targetPosition').textContent=String(globalPosition(state.built)).padStart(2,'0');const c=sectorCard(state.built);$('targetCard').textContent=c?`${c[0]}${SUITS[c[1]]}`:'✓'}$('pauseButton').textContent=state.paused?'▶ RESUME':'Ⅱ PAUSE'}
function restart(){location.reload()}
function tone(freq,duration,volume=.045,type='sine',delay=0,endFreq=freq){if($('soundButton').dataset.muted==='true')return;try{const ctx=tone.ctx||(tone.ctx=new AudioContext()),start=ctx.currentTime+delay,osc=ctx.createOscillator(),gain=ctx.createGain();osc.type=type;osc.frequency.setValueAtTime(freq,start);osc.frequency.exponentialRampToValueAtTime(Math.max(20,endFreq),start+duration);gain.gain.setValueAtTime(volume,start);gain.gain.exponentialRampToValueAtTime(.001,start+duration);osc.connect(gain).connect(ctx.destination);osc.start(start);osc.stop(start+duration)}catch{}}
function noise(duration=.14,volume=.07,delay=0){if($('soundButton').dataset.muted==='true')return;try{const ctx=tone.ctx||(tone.ctx=new AudioContext()),start=ctx.currentTime+delay,buffer=ctx.createBuffer(1,ctx.sampleRate*duration,ctx.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=(Math.random()*2-1)*(1-i/data.length);const source=ctx.createBufferSource(),gain=ctx.createGain(),filter=ctx.createBiquadFilter();source.buffer=buffer;filter.type='lowpass';filter.frequency.value=900;gain.gain.setValueAtTime(volume,start);gain.gain.exponentialRampToValueAtTime(.001,start+duration);source.connect(filter).connect(gain).connect(ctx.destination);source.start(start)}catch{}}
function sound(name){if(name==='select'){tone(330,.045,.018,'sine')}else if(name==='laser'){tone(1050,.13,.032,'sawtooth',0,240);tone(1450,.08,.018,'square',0,500)}else if(name==='enemyLaser'){tone(680,.18,.04,'square',0,140);tone(430,.2,.025,'sawtooth',0,90)}else if(name==='groundLaser'){tone(190,.16,.035,'sine',0,740);tone(1250,.28,.045,'sawtooth',.1,260)}else if(name==='droneBlast'){noise(.3,.09);tone(130,.3,.055,'square',0,38)}else if(name==='impact'){tone(150,.12,.045,'square',0,55)}else if(name==='burn'){noise(.34,.025);tone(92,.32,.018,'sawtooth',0,52)}else if(name==='build'){tone(440,.08);tone(660,.12,.04,'sine',.07)}else if(name==='deploy'){tone(108,2.5,.022,'sawtooth',1,84);tone(216,2.5,.008,'square',1,168)}else if(name==='intercept'){tone(720,.07,.04,'square');tone(1080,.13,.04,'sine',.06)}else if(name==='eliteAlarm'){[0,.55,1.1].forEach(delay=>{tone(790,.34,.045,'square',delay,420);tone(395,.34,.025,'sawtooth',delay,210)})}else if(name==='error'){tone(170,.12,.04,'sawtooth',0,95)}else if(name==='breach'){tone(120,.28,.06,'sawtooth',0,35)}else if(name==='victory'){[523,659,784,1047].forEach((f,i)=>tone(f,.22,.04,'sine',i*.11))}else if(name==='pop'){noise(.1,.05);tone(180,.1,.025,'square',0,55)}else if(name==='highscore'){noise(.28,.09);noise(.22,.08,.18);[392,523,659,784,1047].forEach((f,i)=>tone(f,.3,.045,'sine',i*.1))}}

$('restartButton').onclick=restart;$('pauseButton').onclick=()=>{state.paused=!state.paused;updateUI()};$('soundButton').onclick=e=>{const muted=e.currentTarget.dataset.muted!=='true';e.currentTarget.dataset.muted=muted;e.currentTarget.textContent=muted?'MUTE':'◖))'};
$('tutorialNext').onclick=()=>{const finalStep=state.tutorialStep===activeTutorialSlides().length-1;if(finalStep)finishTutorial();else{state.tutorialStep++;renderTutorialStep()}};window.addEventListener('resize',()=>{if(!$('tutorial').classList.contains('hidden'))renderTutorialStep()});
$('ship').addEventListener('animationiteration',event=>{if(event.animationName==='saucer-bank-patrol'&&state.phase===1)randomizeShipFlight()});randomizeShipFlight();
document.querySelectorAll('[data-stack]').forEach(button=>button.onclick=()=>{state.stackKey=button.dataset.stack;MEMORY_STACK=STACKS[state.stackKey].cards;$('stackChooser').classList.add('hidden');$('selectedStackName').textContent=STACKS[state.stackKey].name;$('modeChooser').classList.remove('hidden');sound('select')});
document.querySelectorAll('[data-mode]').forEach(button=>button.onclick=()=>{state.mode=button.dataset.mode;state.forceTutorial=$('showTutorialToggle').checked;state.positionOrder=state.mode==='super'?shuffle(Array.from({length:52},(_,i)=>i)):Array.from({length:52},(_,i)=>i);state.dronePositionOrder=state.mode==='super'?makeDroneOrder(state.positionOrder):[...state.positionOrder];$('modeChooser').classList.add('hidden');state.sector=0;state.phase=1;state.paused=false;state.ending=false;state.built=0;state.baysBuilt=true;state.turretsDeployed=false;state.score=0;state.sectorStartScore=0;state.damagePenalty=0;state.droneDestroyed=0;state.health=Array(13).fill(0);resetMothership();renderFortress();renderControls();updateUI();if(hasCompletedTutorial()&&!state.forceTutorial)beginMission();else startTutorial();sound('build')});
renderFortress();renderControls();updateUI();
